export interface Course {
  code: string;
  title: string;
  credits: number;
  category: string;
  mandatory: boolean;
}

export const COURSES: Course[] = [
  // Non-Credit / Remedial Courses
  { code: "ENG091", title: "Foundation Course (in English)", credits: 0, category: "Non-Credit", mandatory: false },
  { code: "MAT091", title: "Basic Course in Mathematics I", credits: 0, category: "Non-Credit", mandatory: false },
  { code: "MAT092", title: "Basic Course in Mathematics II", credits: 0, category: "Non-Credit", mandatory: false },

  // GenEd Stream 1
  { code: "ENG101", title: "English Fundamentals", credits: 3, category: "GenEd Stream 1", mandatory: true },
  { code: "ENG102", title: "Composition I", credits: 3, category: "GenEd Stream 1", mandatory: true },
  { code: "ENG103", title: "Advanced Writing Skills and Presentation", credits: 3, category: "GenEd Stream 1", mandatory: false },

  // GenEd Stream 2
  { code: "BIO101", title: "Introduction to Biology", credits: 3, category: "GenEd Stream 2", mandatory: false },
  { code: "CHE101", title: "Introduction to Chemistry", credits: 3, category: "GenEd Stream 2", mandatory: false },
  { code: "CSE101", title: "Introduction to Computer Science", credits: 3, category: "GenEd Stream 2", mandatory: false },
  { code: "ENV103", title: "Elements of Environmental Science", credits: 3, category: "GenEd Stream 2", mandatory: false },
  { code: "MAT101", title: "Fundamentals of Mathematics", credits: 3, category: "GenEd Stream 2", mandatory: false },
  { code: "PHY101", title: "Introduction to Physics", credits: 3, category: "GenEd Stream 2", mandatory: false },
  { code: "STA101", title: "Introduction to Statistics", credits: 3, category: "GenEd Stream 2", mandatory: false },
  { code: "GSC110", title: "Space, Time & Infinity", credits: 3, category: "GenEd Stream 2", mandatory: false },

  // School Core & GenEd Stream 2 Math/Science Courses
  { code: "MAT110", title: "MATH I: Differential Calculus and Co-ordinate Geometry", credits: 3, category: "GenEd Stream 2", mandatory: true },
  { code: "MAT120", title: "MATH II: Integral Calculus and Differential Equations", credits: 3, category: "School Core (Math & Sciences)", mandatory: true },
  { code: "MAT215", title: "MATH III: Complex Variables and Laplace Transformations", credits: 3, category: "School Core (Math & Sciences)", mandatory: true },
  { code: "MAT216", title: "MATH IV: Linear Algebra and Fourier Analysis", credits: 3, category: "School Core (Math & Sciences)", mandatory: true },
  { code: "PHY111", title: "Principles of Physics I", credits: 3, category: "GenEd Stream 2", mandatory: true },
  { code: "PHY112", title: "Principles of Physics II", credits: 3, category: "School Core (Math & Sciences)", mandatory: true },
  { code: "STA201", title: "Elements of Statistics and Probabilities", credits: 3, category: "GenEd Stream 2", mandatory: true },

  // GenEd Stream 3
  { code: "BNG103", title: "Bangla Language and Literature", credits: 3, category: "GenEd Stream 3", mandatory: true },
  { code: "HUM103", title: "Ethics and Culture", credits: 3, category: "GenEd Stream 3", mandatory: true },
  { code: "ENG110", title: "English for Life", credits: 3, category: "GenEd Stream 3", mandatory: false },
  { code: "ENG113", title: "Introduction to English Poetry", credits: 3, category: "GenEd Stream 3", mandatory: false },
  { code: "ENG114", title: "Introduction to English Drama", credits: 3, category: "GenEd Stream 3", mandatory: false },
  { code: "ENG115", title: "Introduction English Prose", credits: 3, category: "GenEd Stream 3", mandatory: false },
  { code: "ENG333", title: "Globalization and the Media", credits: 3, category: "GenEd Stream 3", mandatory: false },
  { code: "HST102", title: "The Modern World", credits: 3, category: "GenEd Stream 3", mandatory: false },
  { code: "HST103", title: "History of Bangladesh", credits: 3, category: "GenEd Stream 3", mandatory: false },
  { code: "HST104", title: "Global History Lab - A History of World since 1300", credits: 3, category: "GenEd Stream 3", mandatory: false },
  { code: "HUM101", title: "World Civilization & Culture", credits: 3, category: "GenEd Stream 3", mandatory: false },
  { code: "HUM102", title: "Introduction to Philosophy", credits: 3, category: "GenEd Stream 3", mandatory: false },
  { code: "HUM207", title: "Narratives of Truth and Lies", credits: 3, category: "GenEd Stream 3", mandatory: false },
  { code: "HUM210", title: "Streaming Media Cultures", credits: 3, category: "GenEd Stream 3", mandatory: false },
  { code: "HUM301", title: "In the Archives", credits: 3, category: "GenEd Stream 3", mandatory: false },

  // GenEd Stream 4
  { code: "EMB101", title: "Emergence of Bangladesh", credits: 3, category: "GenEd Stream 4", mandatory: true },
  { code: "ANT101", title: "Introduction to Anthropology", credits: 3, category: "GenEd Stream 4", mandatory: false },
  { code: "ANT342", title: "Body and Society", credits: 3, category: "GenEd Stream 4", mandatory: false },
  { code: "ANT351", title: "Gender & Development", credits: 3, category: "GenEd Stream 4", mandatory: false },
  { code: "BUS102", title: "Business - Basics, Ethics and Environment", credits: 3, category: "GenEd Stream 4", mandatory: false },
  { code: "BUS201", title: "Business and Human Communication", credits: 3, category: "GenEd Stream 4", mandatory: false },
  { code: "BUS333", title: "Social Entrepreneurship Practicum", credits: 3, category: "GenEd Stream 4", mandatory: false },
  { code: "BUS335", title: "Sustainable Development and Social Enterprise", credits: 3, category: "GenEd Stream 4", mandatory: false },
  { code: "DEV104", title: "Foundations of International Development", credits: 3, category: "GenEd Stream 4", mandatory: false },
  { code: "DEV201", title: "Health, Culture and Development", credits: 3, category: "GenEd Stream 4", mandatory: false },
  { code: "ECO101", title: "Introduction to Microeconomics", credits: 3, category: "GenEd Stream 4", mandatory: false },
  { code: "ECO102", title: "Introduction to Macroeconomics", credits: 3, category: "GenEd Stream 4", mandatory: false },
  { code: "ECO105", title: "Introduction to Economics", credits: 3, category: "GenEd Stream 4", mandatory: false },
  { code: "POL101", title: "Introduction to Political Science", credits: 3, category: "GenEd Stream 4", mandatory: false },
  { code: "POL102", title: "Comparative Governance", credits: 3, category: "GenEd Stream 4", mandatory: false },
  { code: "POL103", title: "International Relations and Global Politics", credits: 3, category: "GenEd Stream 4", mandatory: false },
  { code: "POL201", title: "Introduction to Civic Engagement", credits: 3, category: "GenEd Stream 4", mandatory: false },
  { code: "POL202", title: "Foundations in Public Policy", credits: 3, category: "GenEd Stream 4", mandatory: false },
  { code: "POL203", title: "Political Theory", credits: 3, category: "GenEd Stream 4", mandatory: false },
  { code: "POL210", title: "Youth and Global Movement", credits: 3, category: "GenEd Stream 4", mandatory: false },
  { code: "PSY101", title: "Introduction to Psychology", credits: 3, category: "GenEd Stream 4", mandatory: false },
  { code: "PSY102", title: "Understanding the Human Minds", credits: 3, category: "GenEd Stream 4", mandatory: false },
  { code: "SOC101", title: "Introduction to Sociology", credits: 3, category: "GenEd Stream 4", mandatory: false },
  { code: "SOC201", title: "Social Inequality (ANT202)", credits: 3, category: "GenEd Stream 4", mandatory: false },
  { code: "BU201", title: "Community Engagement and Action", credits: 3, category: "GenEd Stream 4", mandatory: false },

  // GenEd Stream 5
  { code: "CST201", title: "Luxury and Oppression in a Globalized World (of Perfumes)", credits: 3, category: "GenEd Stream 5", mandatory: false },
  { code: "CST204", title: "Communication for Social Change", credits: 3, category: "GenEd Stream 5", mandatory: false },
  { code: "CST301", title: "For the Love of Food", credits: 3, category: "GenEd Stream 5", mandatory: false },
  { code: "CST302", title: "The Pursuit of Wellbeing", credits: 3, category: "GenEd Stream 5", mandatory: false },
  { code: "CST303", title: "Law for Life, Peace and Justice", credits: 3, category: "GenEd Stream 5", mandatory: false },
  { code: "CST304", title: "Documentary Film: Theory and Practice", credits: 3, category: "GenEd Stream 5", mandatory: false },
  { code: "CST305", title: "Borders and Beyond: Past and Future", credits: 3, category: "GenEd Stream 5", mandatory: false },
  { code: "CST306", title: "Ethical Leadership", credits: 3, category: "GenEd Stream 5", mandatory: false },
  { code: "CST307", title: "Art, Community and the Future", credits: 3, category: "GenEd Stream 5", mandatory: false },
  { code: "CST308", title: "Social Dimensions of Faith and Development", credits: 3, category: "GenEd Stream 5", mandatory: false },
  { code: "CST309", title: "Global Citizenship", credits: 3, category: "GenEd Stream 5", mandatory: false },
  { code: "CST310", title: "Social Cohesion and Peace Building", credits: 3, category: "GenEd Stream 5", mandatory: false },
  { code: "CST314", title: "Visual Storytelling: Understanding Society through Documentary Film", credits: 3, category: "GenEd Stream 5", mandatory: false },
  { code: "CST333", title: "Personal Finance for Sustainable Economic Wellbeing", credits: 3, category: "GenEd Stream 5", mandatory: false },
  { code: "BUS334", title: "Social Intrapreneurship Practicum - Leading Change", credits: 3, category: "GenEd Stream 5", mandatory: false },

  // CSE Program Core (Mandatory Core computing + capstone)
  { code: "CSE110", title: "Programming Language I", credits: 3, category: "CSE Program Core", mandatory: true },
  { code: "CSE111", title: "Programming Language II", credits: 3, category: "CSE Program Core", mandatory: true },
  { code: "CSE220", title: "Data Structures", credits: 3, category: "CSE Program Core", mandatory: true },
  { code: "CSE221", title: "Algorithms", credits: 3, category: "CSE Program Core", mandatory: true },
  { code: "CSE230", title: "Discrete Mathematics", credits: 3, category: "CSE Program Core", mandatory: true },
  { code: "CSE250", title: "Circuits and Electronics", credits: 3, category: "CSE Program Core", mandatory: true },
  { code: "CSE251", title: "Electronic Devices and Circuits", credits: 3, category: "CSE Program Core", mandatory: true },
  { code: "CSE260", title: "Digital Logic Design", credits: 3, category: "CSE Program Core", mandatory: true },
  { code: "CSE320", title: "Data Communications", credits: 3, category: "CSE Program Core", mandatory: true },
  { code: "CSE321", title: "Operating Systems", credits: 3, category: "CSE Program Core", mandatory: true },
  { code: "CSE330", title: "Numerical Methods", credits: 3, category: "CSE Program Core", mandatory: true },
  { code: "CSE331", title: "Automata and Computability", credits: 3, category: "CSE Program Core", mandatory: true },
  { code: "CSE340", title: "Computer Architecture", credits: 3, category: "CSE Program Core", mandatory: true },
  { code: "CSE341", title: "Microprocessors", credits: 3, category: "CSE Program Core", mandatory: true },
  { code: "CSE350", title: "Digital Electronics and Pulse Techniques", credits: 3, category: "CSE Program Core", mandatory: true },
  { code: "CSE360", title: "Computer Interfacing", credits: 3, category: "CSE Program Core", mandatory: true },
  { code: "CSE370", title: "Database Systems", credits: 3, category: "CSE Program Core", mandatory: true },
  { code: "CSE420", title: "Compiler Design", credits: 3, category: "CSE Program Core", mandatory: true },
  { code: "CSE421", title: "Computer Networks", credits: 3, category: "CSE Program Core", mandatory: true },
  { code: "CSE422", title: "Artificial Intelligence", credits: 3, category: "CSE Program Core", mandatory: true },
  { code: "CSE423", title: "Computer Graphics", credits: 3, category: "CSE Program Core", mandatory: true },
  { code: "CSE460", title: "VLSI Design", credits: 3, category: "CSE Program Core", mandatory: true },
  { code: "CSE461", title: "Introduction to Robotics", credits: 3, category: "CSE Program Core", mandatory: true },
  { code: "CSE470", title: "Software Engineering", credits: 3, category: "CSE Program Core", mandatory: true },
  { code: "CSE471", title: "Systems Analysis and Design", credits: 3, category: "CSE Program Core", mandatory: true },
  { code: "CSE400", title: "Project and Thesis", credits: 4, category: "CSE Program Core", mandatory: true },

  // CSE Major Electives
  { code: "CSE310", title: "Object-Oriented Programming", credits: 3, category: "CSE Major Elective", mandatory: false },
  { code: "CSE342", title: "Computer Systems Engineering", credits: 3, category: "CSE Major Elective", mandatory: false },
  { code: "CSE371", title: "Management Information Systems", credits: 3, category: "CSE Major Elective", mandatory: false },
  { code: "CSE390", title: "Technical Communication", credits: 3, category: "CSE Major Elective", mandatory: false },
  { code: "CSE391", title: "Programming for the Internet", credits: 3, category: "CSE Major Elective", mandatory: false },
  { code: "CSE392", title: "Signals and Systems", credits: 3, category: "CSE Major Elective", mandatory: false },
  { code: "CSE410", title: "Advance Programming In UNIX", credits: 3, category: "CSE Major Elective", mandatory: false },
  { code: "CSE419", title: "Programming Languages and Competitive Programming", credits: 3, category: "CSE Major Elective", mandatory: false },
  { code: "CSE424", title: "Pattern Recognition", credits: 3, category: "CSE Major Elective", mandatory: false },
  { code: "CSE425", title: "Neural Networks", credits: 3, category: "CSE Major Elective", mandatory: false },
  { code: "CSE426", title: "Advanced Algorithms", credits: 3, category: "CSE Major Elective", mandatory: false },
  { code: "CSE427", title: "Machine Learning", credits: 3, category: "CSE Major Elective", mandatory: false },
  { code: "CSE428", title: "Image Processing", credits: 3, category: "CSE Major Elective", mandatory: false },
  { code: "CSE429", title: "Basic Multimedia Theory", credits: 3, category: "CSE Major Elective", mandatory: false },
  { code: "CSE430", title: "Digital Signal Processing", credits: 3, category: "CSE Major Elective", mandatory: false },
  { code: "CSE431", title: "Natural Language Processing", credits: 3, category: "CSE Major Elective", mandatory: false },
  { code: "CSE432", title: "Speech Recognition and Synthesis", credits: 3, category: "CSE Major Elective", mandatory: false },
  { code: "CSE462", title: "Fault-Tolerant Systems", credits: 3, category: "CSE Major Elective", mandatory: false },
  { code: "CSE472", title: "Human-Computer Interface", credits: 3, category: "CSE Major Elective", mandatory: false },
  { code: "CSE473", title: "Financial Engineering & Technology", credits: 3, category: "CSE Major Elective", mandatory: false },
  { code: "CSE474", title: "Simulation and Modeling", credits: 3, category: "CSE Major Elective", mandatory: false },
  { code: "CSE490", title: "Special Topics / WAN Routing and Technologies", credits: 3, category: "CSE Major Elective", mandatory: false },
  { code: "CSE491", title: "Independent Study", credits: 3, category: "CSE Major Elective", mandatory: false }
];

export interface PrereqRule {
  hp: string[];
  sp: string[];
}

export const PREREQUISITES: Record<string, PrereqRule> = {
  "MAT092": { "hp": ["MAT091"], "sp": [] },
  "ENG101": { "hp": ["ENG091"], "sp": [] },
  "ENG102": { "hp": ["ENG101"], "sp": [] },
  "ENG103": { "hp": ["ENG102"], "sp": [] },
  "MAT120": { "hp": ["MAT110"], "sp": [] },
  "MAT216": { "hp": ["MAT120"], "sp": [] },
  "MAT215": { "hp": ["MAT216"], "sp": [] },
  "PHY112": { "hp": ["PHY111"], "sp": [] },
  "CSE111": { "hp": ["CSE110"], "sp": [] },
  "CSE220": { "hp": ["CSE111", "CSE230"], "sp": [] },
  "CSE221": { "hp": ["CSE220"], "sp": [] },
  "CSE250": { "hp": [], "sp": ["PHY112"] },
  "CSE251": { "hp": ["CSE250"], "sp": [] },
  "CSE260": { "hp": ["CSE251"], "sp": [] },
  "CSE320": { "hp": [], "sp": [] },
  "CSE321": { "hp": ["CSE221"], "sp": [] },
  "CSE330": { "hp": ["MAT216"], "sp": [] },
  "CSE331": { "hp": ["CSE221"], "sp": [] },
  "CSE340": { "hp": [], "sp": ["CSE260"] },
  "CSE341": { "hp": [], "sp": ["CSE321", "CSE330"] },
  "CSE350": { "hp": ["CSE251"], "sp": [] },
  "CSE360": { "hp": ["CSE341"], "sp": [] },
  "CSE370": { "hp": ["CSE221"], "sp": [] },
  "CSE420": { "hp": ["CSE321", "CSE331", "CSE340"], "sp": [] },
  "CSE421": { "hp": [], "sp": ["CSE320"] },
  "CSE422": { "hp": ["CSE221"], "sp": [] },
  "CSE423": { "hp": ["MAT216"], "sp": [] },
  "CSE460": { "hp": ["CSE260"], "sp": [] },
  "CSE461": { "hp": ["CSE260"], "sp": [] },
  "CSE470": { "hp": ["CSE370"], "sp": [] },
  "CSE471": { "hp": ["CSE370"], "sp": [] },
  "CSE400": { "hp": ["CSE370", "CSE470", "CSE321"], "sp": [] },
  "CSE310": { "hp": ["CSE111"], "sp": [] },
  "CSE342": { "hp": ["CSE340"], "sp": [] },
  "CSE371": { "hp": ["CSE370"], "sp": [] },
  "CSE390": { "hp": ["ENG102"], "sp": [] },
  "CSE391": { "hp": ["CSE220"], "sp": [] },
  "CSE392": { "hp": ["MAT215", "MAT216"], "sp": [] },
  "CSE410": { "hp": ["CSE321"], "sp": [] },
  "CSE419": { "hp": ["CSE221"], "sp": [] },
  "CSE424": { "hp": ["CSE221", "STA201"], "sp": [] },
  "CSE425": { "hp": ["CSE221", "STA201"], "sp": [] },
  "CSE426": { "hp": ["CSE221"], "sp": [] },
  "CSE427": { "hp": ["CSE221", "STA201", "MAT216"], "sp": [] },
  "CSE428": { "hp": ["CSE221", "MAT216"], "sp": [] },
  "CSE429": { "hp": ["CSE221"], "sp": [] },
  "CSE430": { "hp": ["MAT215", "MAT216"], "sp": [] },
  "CSE431": { "hp": ["CSE221"], "sp": [] },
  "CSE432": { "hp": ["CSE221", "STA201"], "sp": [] },
  "CSE462": { "hp": ["CSE340"], "sp": [] },
  "CSE472": { "hp": ["CSE370"], "sp": [] },
  "CSE473": { "hp": ["CSE221", "STA201"], "sp": [] },
  "CSE474": { "hp": ["STA201", "CSE220"], "sp": [] },
  "CSE490": { "hp": ["CSE320", "CSE321"], "sp": [] },
  "CSE491": { "hp": ["CSE400"], "sp": [] }
};
